name: hybran
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.80 # we require SeqFeature equality testing
  - blast
  - cd-hit
  - diamond
  - dill
  - eggnog-mapper
  - emboss
  - entrez-direct
  - frozendict
  - intervaltree
  - mcl
  - multiprocess
  - mummer
  - networkx
  - paml
  - prokka>=1.14.0 # for prokka's --coverage
  - python>=3.12
  - ratt
  - tbl2asn-forever
